/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Conexao;
import classes.ConverteMoeda;
import java.applet.AudioClip;
import java.awt.Image;
import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import java.sql.ResultSet;

/**
 *
 * @author Aluno
 */
public class TelaMachine extends javax.swing.JFrame {

    /**
     * Creates new form Machine2
     */
    public TelaMachine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbimg1 = new javax.swing.JLabel();
        lbimg2 = new javax.swing.JLabel();
        lbimg3 = new javax.swing.JLabel();
        lbimg4 = new javax.swing.JLabel();
        lbimg5 = new javax.swing.JLabel();
        lbimg6 = new javax.swing.JLabel();
        lbimg7 = new javax.swing.JLabel();
        lbimg8 = new javax.swing.JLabel();
        lbimg9 = new javax.swing.JLabel();
        lbpreco1 = new javax.swing.JLabel();
        lbpreco2 = new javax.swing.JLabel();
        lbpreco3 = new javax.swing.JLabel();
        lbpreco4 = new javax.swing.JLabel();
        lbpreco5 = new javax.swing.JLabel();
        lbpreco6 = new javax.swing.JLabel();
        lbpreco7 = new javax.swing.JLabel();
        lbpreco8 = new javax.swing.JLabel();
        lbpreco9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        lbtroco = new javax.swing.JLabel();
        lbvisor = new javax.swing.JLabel();
        lbcedula2 = new javax.swing.JLabel();
        lbcedula5 = new javax.swing.JLabel();
        lbcedula10 = new javax.swing.JLabel();
        lbcedula20 = new javax.swing.JLabel();
        lbcedula50 = new javax.swing.JLabel();
        lbdispenser = new javax.swing.JLabel();
        btnretiratroco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(138, 90, 68));

        jPanel2.setBackground(new java.awt.Color(195, 142, 111));

        lbimg1.setToolTipText("");
        lbimg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbimg2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbimg3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbimg4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbimg5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbimg6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbimg7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbimg8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbimg9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbpreco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco1.setText(" ");

        lbpreco2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco2.setText(" ");

        lbpreco3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco3.setText(" ");

        lbpreco4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco4.setText(" ");

        lbpreco5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco5.setText(" ");

        lbpreco6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco6.setText(" ");

        lbpreco7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco7.setText(" ");

        lbpreco8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco8.setText(" ");

        lbpreco9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpreco9.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbpreco7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lbpreco8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbimg4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbimg5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbimg2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbpreco5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbpreco2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbimg7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbimg8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbpreco4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbpreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbimg6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbimg3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(lbimg9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbpreco6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbpreco3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbpreco9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbimg3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbimg2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbpreco3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbpreco1)
                        .addComponent(lbpreco2)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbimg5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbimg4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbimg6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbpreco5)
                    .addComponent(lbpreco4)
                    .addComponent(lbpreco6))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbimg8, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(lbimg7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbimg9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbpreco7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbpreco9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbpreco8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(195, 142, 111));

        btn1.setText("1");
        btn1.setBorder(null);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.setBorder(null);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.setBorder(null);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.setBorder(null);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.setBorder(null);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.setBorder(null);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.setBorder(null);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.setBorder(null);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.setBorder(null);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        lbtroco.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lbtroco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtroco.setText("TROCO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addComponent(lbtroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lbtroco)
                .addGap(30, 30, 30))
        );

        lbvisor.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lbvisor.setForeground(new java.awt.Color(255, 255, 255));
        lbvisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbvisor.setText("VALOR");

        lbcedula2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbcedula2MouseClicked(evt);
            }
        });

        lbcedula5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbcedula5MouseClicked(evt);
            }
        });

        lbcedula10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbcedula10MouseClicked(evt);
            }
        });

        lbcedula20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbcedula20MouseClicked(evt);
            }
        });

        lbcedula50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbcedula50MouseClicked(evt);
            }
        });

        lbdispenser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbdispenser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbdispenserMouseClicked(evt);
            }
        });

        btnretiratroco.setText("Pega o troco mané");
        btnretiratroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretiratrocoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbcedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbcedula5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbcedula10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lbcedula20, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbcedula50, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbvisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(lbdispenser, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnretiratroco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbcedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcedula5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcedula10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbcedula20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcedula50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(lbvisor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbdispenser, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnretiratroco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    JLabel[] lbfotos;
    JLabel[] lbprecos;
    JButton[] btnescolha;
    JLabel[] lbcedulas;
    double dinheiro;
    int[] codigo = new int[9];
    double[] preco = new double[9];
    private double valor_compra = 0;
    ConverteMoeda cm = new ConverteMoeda();
    Conexao con;
    int indice;
    AudioClip Som;
    
    private void carregaprodutos(){
        dinheiro=0;
        lbfotos=new JLabel[]{lbimg1,lbimg2,lbimg3,lbimg4,lbimg5,lbimg6,lbimg7,lbimg8,lbimg9};
        lbprecos=new JLabel[]{lbpreco1,lbpreco2,lbpreco3,lbpreco4,lbpreco5,lbpreco6,lbpreco7,lbpreco8,lbpreco9};
        btnescolha=new JButton[]{btn1,btn2,btn3,btn4,btn5,btn6,btn7,btn8,btn9};
        lbcedulas=new JLabel[]{lbcedula2,lbcedula5,lbcedula10,lbcedula20,lbcedula50};
        for(int i=0; i<5; i++){
            ImageIcon imagem = new  ImageIcon(this.getClass().getResource("/img/ced"+(i+1)+".png"));       
            Image imag = imagem.getImage().getScaledInstance(lbcedulas[i].getWidth(), lbcedulas[i].getHeight(), Image.SCALE_DEFAULT); 
            lbcedulas[i].setIcon(new ImageIcon(imag));
        }
        /* carregar imagem da pasta
        for(int i=0; i<9; i++){
            ImageIcon imagem = new  ImageIcon(this.getClass().getResource("/img/bebi"+(i+1)+".png"));       
            Image imag = imagem.getImage().getScaledInstance(lbfotos[i].getWidth(), lbfotos[i].getHeight(), Image.SCALE_DEFAULT); 
            lbfotos[i].setIcon(new ImageIcon(imag));
        }
        carregar imagem do banco
        */
        String sql = "select * from tb01_produtos";
        con = new Conexao();
        try {
            con.conectar();
            ResultSet rs = con.selectSQL(sql);
            int i=0;
            while(rs.next()){
                codigo[i]=rs.getInt("tb01_cod");
                preco[i]=rs.getDouble("tb01_preco");
                if(rs.getInt("tb01_qtde")>0){
                    lbprecos[i].setText(cm.ConvMoeda(rs.getString("tb01_preco")));
                    ImageIcon imagem = new  ImageIcon(rs.getBytes("tb01_foto"));
                    Image imag = imagem.getImage().getScaledInstance(lbfotos[i].getWidth(), lbfotos[i].getHeight(), Image.SCALE_DEFAULT); 
                    lbfotos[i].setIcon(new ImageIcon(imag));
                } else {
                    lbprecos[i].setText(null);
                    lbfotos[i].setIcon(null);
                    btnescolha[i].setEnabled(false);
                }
                i++;
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaMachine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaMachine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void movimento(final JLabel fig)
        {             
            new Thread()
            {
                public void run()
                { 
                    Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/saindo.wav")); 
                    Som.stop();
                    Som.play();
                   int y = fig.getLocation().y;
                   int x = fig.getLocation().x;
                   int z = lbdispenser.getLocation().y;            

                    while(y <= z)
                    {
                        y = y + 1; 
                        fig.setLocation(x,y);

                        try
                        {
                            sleep(6);
                        }
                        catch (Exception e)
                        {
                        }
                    }
               
                    lbdispenser.setIcon(fig.getIcon());  
                    fig.setIcon(null);
                }
            }.start();
        }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregaprodutos();
        travar();
    }//GEN-LAST:event_formWindowOpened

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/digito.wav")); 
        Som.stop();
        Som.play();
        btnescolha[0].setEnabled(false);
        if(dinheiro<2){
            btnescolha[0].setEnabled(false);
        } else {
            movimento(lbfotos[0]);
            valor_compra = 2;
        }
        indice=0;
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/digito.wav")); 
        Som.stop();
        Som.play();
        btnescolha[1].setEnabled(false);
        if(dinheiro<14){
            btnescolha[1].setEnabled(false);
        } else {
            movimento(lbfotos[1]);
            valor_compra = valor_compra + 14;
        }
        indice=1;
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/digito.wav")); 
        Som.stop();
        Som.play();
        btnescolha[2].setEnabled(false);
        if(dinheiro<8){
            btnescolha[2].setEnabled(false);
        } else {
            movimento(lbfotos[2]);
            valor_compra = valor_compra + 8;
        }
        indice=2;
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/digito.wav")); 
        Som.stop();
        Som.play();
        btnescolha[3].setEnabled(false);
        if(dinheiro<10){
            btnescolha[3].setEnabled(false);
        } else {
            movimento(lbfotos[3]);
            valor_compra = valor_compra + 10;
        }
        indice=3;
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/digito.wav")); 
        Som.stop();
        Som.play();
        btnescolha[4].setEnabled(false);
        if(dinheiro<7){
            btnescolha[4].setEnabled(false);
        } else {
            movimento(lbfotos[4]);
            valor_compra = valor_compra + 7;
        }
        indice=4;
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/digito.wav")); 
        Som.stop();
        Som.play();
        btnescolha[5].setEnabled(false);
        if(dinheiro<6){
            btnescolha[5].setEnabled(false);
        } else {
            movimento(lbfotos[5]);
            valor_compra = valor_compra + 6;
        }
        indice=5;
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/digito.wav")); 
        Som.stop();
        Som.play();
        btnescolha[6].setEnabled(false);
        if(dinheiro<8){
            btnescolha[6].setEnabled(false);
        } else {
            movimento(lbfotos[6]);
            valor_compra = valor_compra + 8;
        }
        indice=6;
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/digito.wav")); 
        Som.stop();
        Som.play();
        btnescolha[7].setEnabled(false);
        if(dinheiro<12){
            btnescolha[7].setEnabled(false);
        } else {
            movimento(lbfotos[7]);
            valor_compra = valor_compra + 12;
        }
        indice=7;
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/digito.wav")); 
        Som.stop();
        Som.play();
        btnescolha[8].setEnabled(false);
        if(dinheiro<9){
            btnescolha[8].setEnabled(false);
        } else {
            movimento(lbfotos[8]);
            valor_compra = valor_compra + 9;
        }
        indice=8;
    }//GEN-LAST:event_btn9ActionPerformed

    private void lbcedula2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcedula2MouseClicked
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/dinheiro.wav")); 
        Som.stop();
        Som.play();
        dinheiro+=2;
        lbvisor.setText(cm.ConvMoeda(String.valueOf(dinheiro)));
        destravar();
    }//GEN-LAST:event_lbcedula2MouseClicked

    private void lbcedula5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcedula5MouseClicked
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/dinheiro.wav")); 
        Som.stop();
        Som.play();
        dinheiro+=5;
        lbvisor.setText(cm.ConvMoeda(String.valueOf(dinheiro)));
        destravar();
    }//GEN-LAST:event_lbcedula5MouseClicked

    private void lbcedula10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcedula10MouseClicked
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/dinheiro.wav")); 
        Som.stop();
        Som.play();
        dinheiro+=10;
        lbvisor.setText(cm.ConvMoeda(String.valueOf(dinheiro)));
        destravar();
    }//GEN-LAST:event_lbcedula10MouseClicked

    private void lbcedula20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcedula20MouseClicked
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/dinheiro.wav")); 
        Som.stop();
        Som.play();
        dinheiro+=20;
        lbvisor.setText(cm.ConvMoeda(String.valueOf(dinheiro)));
        destravar();
    }//GEN-LAST:event_lbcedula20MouseClicked

    private void lbcedula50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbcedula50MouseClicked
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/dinheiro.wav")); 
        Som.stop();
        Som.play();
        dinheiro+=50;
        lbvisor.setText(cm.ConvMoeda(String.valueOf(dinheiro)));
        destravar();
    }//GEN-LAST:event_lbcedula50MouseClicked

    private void lbdispenserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbdispenserMouseClicked
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/retirar.wav")); 
        Som.stop();
        Som.play();
        String sql = "update tb01_produtos set tb01_qtde=tb01_qtde-1 where tb01_cod="+codigo[indice];
        con = new Conexao();
        try {
            con.conectar();
            con.runSQL(sql);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaMachine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaMachine.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        double troco = dinheiro - valor_compra;
        lbtroco.setText("R$ " + troco);
        lbvisor.setText("VALOR");
        lbdispenser.setIcon(null);
        dinheiro = 0;
        valor_compra = 0;
        carregaprodutos();
    }//GEN-LAST:event_lbdispenserMouseClicked

    private void btnretiratrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretiratrocoActionPerformed
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/troco.wav")); 
        Som.stop();
        Som.play();
        lbtroco.setText("TROCO");
        valor_compra = 0;
        travar();
    }//GEN-LAST:event_btnretiratrocoActionPerformed

    private void travar(){
        for(int i=0; i<9; i++){
            btnescolha[i].setEnabled(false);
        }
    }
    
    private void destravar() {
        String sql = "select * from tb01_produtos";
        con = new Conexao();
        try {
            con.conectar();
            ResultSet rs = con.selectSQL(sql);
            int i = 0;
            while (rs.next()) {
                int quantidade = rs.getInt("tb01_qtde");
                if (dinheiro >= preco[i] && quantidade > 0) {
                    btnescolha[i].setEnabled(true);
                } else {
                    btnescolha[i].setEnabled(false);
                    if (quantidade <= 0) {
                        lbfotos[i].setIcon(null);
                    }
                }
                i++;
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaMachine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaMachine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnretiratroco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbcedula10;
    private javax.swing.JLabel lbcedula2;
    private javax.swing.JLabel lbcedula20;
    private javax.swing.JLabel lbcedula5;
    private javax.swing.JLabel lbcedula50;
    private javax.swing.JLabel lbdispenser;
    private javax.swing.JLabel lbimg1;
    private javax.swing.JLabel lbimg2;
    private javax.swing.JLabel lbimg3;
    private javax.swing.JLabel lbimg4;
    private javax.swing.JLabel lbimg5;
    private javax.swing.JLabel lbimg6;
    private javax.swing.JLabel lbimg7;
    private javax.swing.JLabel lbimg8;
    private javax.swing.JLabel lbimg9;
    private javax.swing.JLabel lbpreco1;
    private javax.swing.JLabel lbpreco2;
    private javax.swing.JLabel lbpreco3;
    private javax.swing.JLabel lbpreco4;
    private javax.swing.JLabel lbpreco5;
    private javax.swing.JLabel lbpreco6;
    private javax.swing.JLabel lbpreco7;
    private javax.swing.JLabel lbpreco8;
    private javax.swing.JLabel lbpreco9;
    private javax.swing.JLabel lbtroco;
    private javax.swing.JLabel lbvisor;
    // End of variables declaration//GEN-END:variables
}
