/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import classes.Som;
import java.applet.AudioClip;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.util.Random;

/**
 *
 * @author aluno
 */
public class Jogo extends javax.swing.JFrame {
    JLabel[] jlarvores;
    JLabel[] jlbala;
        Random rand = new Random(); 
        int upperbound = 10;
        int marciano = rand.nextInt(upperbound); 
        int bala=0;
        AudioClip Som;
        
    /**
     * Creates new form jogo
     */
    public Jogo() {
        initComponents();
        jlarvores = new JLabel[]{lbarvore1, lbarvore2, lbarvore3, lbarvore4, lbarvore5, lbarvore6, lbarvore7, lbarvore8, lbarvore9, lbarvore10};
        jlbala = new JLabel[]{lbbala1, lbbala2, lbbala3};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbarvore1 = new javax.swing.JLabel();
        lbarvore2 = new javax.swing.JLabel();
        lbarvore3 = new javax.swing.JLabel();
        lbarvore4 = new javax.swing.JLabel();
        lbarvore5 = new javax.swing.JLabel();
        lbarvore6 = new javax.swing.JLabel();
        lbarvore7 = new javax.swing.JLabel();
        lbarvore8 = new javax.swing.JLabel();
        lbarvore9 = new javax.swing.JLabel();
        lbarvore10 = new javax.swing.JLabel();
        lbaviso = new javax.swing.JLabel();
        lbbala1 = new javax.swing.JLabel();
        lbbala2 = new javax.swing.JLabel();
        lbbala3 = new javax.swing.JLabel();
        lbiniciar = new javax.swing.JButton();
        lbfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbarvore1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbarvore1MouseClicked(evt);
            }
        });
        getContentPane().add(lbarvore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 120, 210));

        lbarvore2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbarvore2MouseClicked(evt);
            }
        });
        getContentPane().add(lbarvore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 120, 210));

        lbarvore3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbarvore3MouseClicked(evt);
            }
        });
        getContentPane().add(lbarvore3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 120, 210));

        lbarvore4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbarvore4MouseClicked(evt);
            }
        });
        getContentPane().add(lbarvore4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 120, 210));

        lbarvore5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbarvore5MouseClicked(evt);
            }
        });
        getContentPane().add(lbarvore5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 120, 210));

        lbarvore6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbarvore6MouseClicked(evt);
            }
        });
        getContentPane().add(lbarvore6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 120, 210));

        lbarvore7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbarvore7MouseClicked(evt);
            }
        });
        getContentPane().add(lbarvore7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 120, 210));

        lbarvore8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbarvore8MouseClicked(evt);
            }
        });
        getContentPane().add(lbarvore8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 120, 210));

        lbarvore9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbarvore9MouseClicked(evt);
            }
        });
        getContentPane().add(lbarvore9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 280, 120, 210));

        lbarvore10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbarvore10MouseClicked(evt);
            }
        });
        getContentPane().add(lbarvore10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 280, 120, 210));

        lbaviso.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        lbaviso.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbaviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 700, 60));
        getContentPane().add(lbbala1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, 60));
        getContentPane().add(lbbala2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 60, 60));
        getContentPane().add(lbbala3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 60, 60));

        lbiniciar.setText("Iniciar");
        lbiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbiniciarMouseClicked(evt);
            }
        });
        lbiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(lbiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, -1, -1));
        getContentPane().add(lbfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        comecar();
    }//GEN-LAST:event_formWindowOpened

    private void comecar(){
        ImageIcon imagem = new  ImageIcon(this.getClass().getResource("/img/floresta.jpg"));       
        Image imag = imagem.getImage().getScaledInstance(lbfundo.getWidth(), lbfundo.getHeight(), Image.SCALE_DEFAULT);
        lbfundo.setIcon(new ImageIcon(imag)); 
        for(int i=0; i<10; i++){
            imagem = new  ImageIcon(this.getClass().getResource("/img/arvore.png"));       
            imag = imagem.getImage().getScaledInstance(jlarvores[i].getWidth(), jlarvores[i].getHeight(), Image.SCALE_DEFAULT);
            jlarvores[i].setIcon(new ImageIcon(imag)); 
        }
        for(int i=0; i<3; i++){
            imagem = new  ImageIcon(this.getClass().getResource("/img/bala.png"));       
            imag = imagem.getImage().getScaledInstance(jlbala[i].getWidth(), jlbala[i].getHeight(), Image.SCALE_DEFAULT);
            jlbala[i].setIcon(new ImageIcon(imag));
        }
        bala=0;
        lbaviso.setText("");
        Random rand = new Random(); 
        upperbound = 10;
        marciano = rand.nextInt(upperbound); 
        Som = java.applet.Applet.newAudioClip(getClass().getResource("/som/what-is-love...baby-don't-hurt-me.wav")); 
        Som.stop();
    }
    
    private void achar(int arvore){

        if(bala < 3){
            if(arvore > marciano){
                lbaviso.setText("Errou! Estou mais a esquerda.");
                ImageIcon imagem = new  ImageIcon(this.getClass().getResource("/img/abala.png"));       
                Image imag = imagem.getImage().getScaledInstance(jlbala[bala].getWidth(), jlbala[bala].getHeight(), Image.SCALE_DEFAULT);
                jlbala[bala].setIcon(new ImageIcon(imag));
                ImageIcon imagem1 = new  ImageIcon(this.getClass().getResource("/img/arvore2.png"));       
                Image imag1 = imagem1.getImage().getScaledInstance(jlarvores[arvore-1].getWidth(), jlarvores[arvore-1].getHeight(), Image.SCALE_DEFAULT);
                jlarvores[arvore-1].setIcon(new ImageIcon(imag1));
                bala++;
            }
            if(arvore < marciano){
                lbaviso.setText("Errou! Estou mais a direita.");
                ImageIcon imagem = new  ImageIcon(this.getClass().getResource("/img/abala.png"));       
                Image imag = imagem.getImage().getScaledInstance(jlbala[bala].getWidth(), jlbala[bala].getHeight(), Image.SCALE_DEFAULT);
                jlbala[bala].setIcon(new ImageIcon(imag)); 
                ImageIcon imagem1 = new  ImageIcon(this.getClass().getResource("/img/arvore2.png"));       
                Image imag1 = imagem1.getImage().getScaledInstance(jlarvores[arvore-1].getWidth(), jlarvores[arvore-1].getHeight(), Image.SCALE_DEFAULT);
                jlarvores[arvore-1].setIcon(new ImageIcon(imag1));
                bala++;
            }
            if(arvore == marciano){
                lbaviso.setText("Maldito! Você me acertou!");
                ImageIcon imagem = new  ImageIcon(this.getClass().getResource("/img/marciano.png"));       
                Image imag = imagem.getImage().getScaledInstance(jlarvores[marciano-1].getWidth(), jlarvores[marciano-1].getHeight(), Image.SCALE_DEFAULT);
                jlarvores[marciano-1].setIcon(new ImageIcon(imag)); 
                bala = 4;
                Som.play();
            }
        }
        if(bala == 3){
            lbaviso.setText("Haha! Acabou suas balas, vou te pegar!");
        }
    }
    
    private void lbarvore1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbarvore1MouseClicked
        achar(1);
    }//GEN-LAST:event_lbarvore1MouseClicked

    private void lbarvore2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbarvore2MouseClicked
        achar(2);
    }//GEN-LAST:event_lbarvore2MouseClicked

    private void lbarvore3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbarvore3MouseClicked
        achar(3);
    }//GEN-LAST:event_lbarvore3MouseClicked

    private void lbarvore4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbarvore4MouseClicked
        achar(4);
    }//GEN-LAST:event_lbarvore4MouseClicked

    private void lbarvore5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbarvore5MouseClicked
        achar(5);
    }//GEN-LAST:event_lbarvore5MouseClicked

    private void lbarvore6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbarvore6MouseClicked
        achar(6);
    }//GEN-LAST:event_lbarvore6MouseClicked

    private void lbarvore7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbarvore7MouseClicked
        achar(7);
    }//GEN-LAST:event_lbarvore7MouseClicked

    private void lbarvore8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbarvore8MouseClicked
        achar(8);
    }//GEN-LAST:event_lbarvore8MouseClicked

    private void lbarvore9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbarvore9MouseClicked
        achar(9);
    }//GEN-LAST:event_lbarvore9MouseClicked

    private void lbarvore10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbarvore10MouseClicked
        achar(10);
    }//GEN-LAST:event_lbarvore10MouseClicked

    private void lbiniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbiniciarMouseClicked
        comecar();
        Som.stop();
    }//GEN-LAST:event_lbiniciarMouseClicked

    private void lbiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbiniciarActionPerformed
        comecar();
    }//GEN-LAST:event_lbiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbarvore1;
    private javax.swing.JLabel lbarvore10;
    private javax.swing.JLabel lbarvore2;
    private javax.swing.JLabel lbarvore3;
    private javax.swing.JLabel lbarvore4;
    private javax.swing.JLabel lbarvore5;
    private javax.swing.JLabel lbarvore6;
    private javax.swing.JLabel lbarvore7;
    private javax.swing.JLabel lbarvore8;
    private javax.swing.JLabel lbarvore9;
    private javax.swing.JLabel lbaviso;
    private javax.swing.JLabel lbbala1;
    private javax.swing.JLabel lbbala2;
    private javax.swing.JLabel lbbala3;
    private javax.swing.JLabel lbfundo;
    private javax.swing.JButton lbiniciar;
    // End of variables declaration//GEN-END:variables
}
